"""decouple conversation_sessions from users

Revision ID: f720bd505a9e
Revises: be847b18f252
Create Date: 2026-09-15 13:09:50.446431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f720bd505a9e'
down_revision: Union[str, Sequence[str], None] = 'be847b18f252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_sessions', sa.Column('phone_number', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_conversation_sessions_phone_number'), 'conversation_sessions', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_sessions_phone_number'), table_name='conversation_sessions')
    op.drop_column('conversation_sessions', 'phone_number')
    # ### end Alembic commands ###
